@ApiWebMinima_HostAddress = https://localhost:7266

POST {{ApiWebMinima_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"bbaab",
  "isComplete":true
}

###

GET {{ApiWebMinima_HostAddress}}/

###

GET {{ApiWebMinima_HostAddress}}/todoitems

###

GET {{ApiWebMinima_HostAddress}}/todoitems/3

###

PUT {{ApiWebMinima_HostAddress}}/todoitems/3
Content-Type: application/json

{
  "name":"David",
  "isComplete":true
}

###

DELETE {{ApiWebMinima_HostAddress}}/todoitems/2

###
